Description: >
    This is an example of a long running ECS service that responds to HTTP
    requests with a single word.
Parameters:

    VPC:
        Type: AWS::EC2::VPC::Id
    Listener:
        Type: String
    EnvironmentName:
        Type: String
    RepositoryUri:
        Type: String
    Subnets:
        Type: List<AWS::EC2::Subnet::Id>
    ECSServicesSecurityGroup:
        Type: AWS::EC2::SecurityGroup::Id

Resources:

    Cluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: !Ref EnvironmentName

    Service:
        Type: AWS::ECS::Service
        DependsOn: ListenerRule
        Properties:
            Cluster: !Ref Cluster
            LaunchType: FARGATE
            DesiredCount: 2
            DeploymentConfiguration:
                MaximumPercent: 150
                MinimumHealthyPercent: 100
            TaskDefinition: !Ref TaskDefinition
            NetworkConfiguration:
                AwsvpcConfiguration:
                    Subnets: !Ref Subnets
                    AssignPublicIp: ENABLED
                    SecurityGroups:
                        - !Ref ECSServicesSecurityGroup
            LoadBalancers:
                - ContainerName: !Ref EnvironmentName
                  ContainerPort: 8080
                  TargetGroupArn: !Ref TargetGroup

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            TaskRoleArn: !GetAtt TaskExecutionRole.Arn
            ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
            Cpu: 256
            Memory: 512
            Family: !Ref EnvironmentName
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
            ContainerDefinitions:
                - Name: !Ref EnvironmentName
                  Essential: true
                  Image: !Sub ${RepositoryUri}:latest
                  PortMappings:
                      - ContainerPort: 8080
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-group: !Ref EnvironmentName
                          awslogs-region: !Ref AWS::Region
                          awslogs-stream-prefix: ecs

    LogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Ref EnvironmentName
            RetentionInDays: 365

    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            VpcId: !Ref VPC
            Port: 8080
            Protocol: HTTP
            Matcher:
                HttpCode: 200-299
            HealthCheckIntervalSeconds: 40
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 20
            HealthyThresholdCount: 2
            TargetType: ip
            TargetGroupAttributes:
                - Key: deregistration_delay.timeout_seconds
                  Value: '10'

    ListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref Listener
            Priority: 1
            Conditions:
                - Field: path-pattern
                  Values:
                    - "*"
            Actions:
                - TargetGroupArn: !Ref TargetGroup
                  Type: forward

    TaskExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Principal:
                      Service:
                      - ecs-tasks.amazonaws.com
                  Action:
                  - sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:

    EcsServiceArn:
        Description: A reference to the created ECS service ARN
        Value: !Ref Service

    EcsClusterName:
        Description: A reference to the created ECS service ARN
        Value: !Ref Cluster

    EcsTaskExecutionRoleArn:
        Description: A reference to the created IAM role ARN
        Value: !Ref TaskExecutionRole
